"""Generate every SVG in the set from the canonical geometry.

Writes:
    art/logo/mark.svg         full colour, transparent, 64u artboard
    art/logo/mark-mono.svg    currentColor, single flat colour
    art/favicon/favicon.svg   the mark, transparent (see note below)
    art/src/lockup-*.svg      editable lockup sources, live <text>
    art/artboards/*.svg       social / banner / og artboards, live <text>

render.sh then rasterises with resvg and outlines the lockups with usvg.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lockup
import mark as M

HERE = os.path.dirname(os.path.abspath(__file__))
ART = os.path.dirname(HERE)

HEADER = (
    "<!-- Laravel Package Toolkit — {what}\n"
    "     Generated by art/artboards/build.py. Do not hand-edit; edit the\n"
    "     generator and re-run art/render.sh. -->\n"
)


def write(path, svg, what):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(HEADER.format(what=what) + svg + "\n")
    print(path)


def main():
    write(os.path.join(ART, "logo", "mark.svg"), M.svg(), "the mark, full colour")
    write(
        os.path.join(ART, "logo", "mark-mono.svg"),
        M.svg(paint="currentColor"),
        "the mark, one colour, inherits currentColor",
    )
    # The favicon is the bare mark rather than a tile: at 16px a tile spends
    # roughly a fifth of every edge on its own corner radius, and the mark that
    # survives inside it is meaningfully smaller than one drawn edge to edge.
    # The opaque tile is still used for the touch icons, where transparency is
    # either unhelpful or forbidden.
    write(os.path.join(ART, "favicon", "favicon.svg"), M.svg(), "favicon, the bare mark")

    lockup.main()


if __name__ == "__main__":
    main()
